logging:
  level: "info"
  format: "combined"
  transports:
    console:
      enabled: true
      colorize: true
    file:
      enabled: true
      filename: "logs/main.yml"
      maxsize: 10485760
      maxFiles: 5
  errorHandling:
    captureStackTrace: true
    logUncaughtExceptions: true
    logUnhandledRejections: true
